/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_starxg_keytar_Keytar */

#ifndef _Included_com_starxg_keytar_Keytar
#define _Included_com_starxg_keytar_Keytar
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     com_starxg_keytar_Keytar
 * Method:    _getPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
  JNIEXPORT jstring JNICALL Java_com_starxg_keytar_Keytar__1getPassword(JNIEnv *, jobject, jstring, jstring);

  /*
 * Class:     com_starxg_keytar_Keytar
 * Method:    _setPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
  JNIEXPORT void JNICALL Java_com_starxg_keytar_Keytar__1setPassword(JNIEnv *, jobject, jstring, jstring, jstring);

  /*
 * Class:     com_starxg_keytar_Keytar
 * Method:    _deletePassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
  JNIEXPORT jboolean JNICALL Java_com_starxg_keytar_Keytar__1deletePassword(JNIEnv *, jobject, jstring, jstring);

  /*
 * Class:     com_starxg_keytar_Keytar
 * Method:    _getCredentials
 * Signature: (Ljava/lang/String;)Ljava/util/Map;
 */
  JNIEXPORT jobject JNICALL Java_com_starxg_keytar_Keytar__1getCredentials(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
